<a href="https://colab.research.google.com/github/hymnofgod/machinelearning/blob/main/introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Single dimension array


INTRODUCTION to numpy

what we will cover:

1.creating arrays
2.multidimensiomal arrays
3.Randomly generated arrays
4.Element wise operation
5.Summarization operation

In [2]:
import numpy as np


In [3]:
# create an array with all elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# create an array with all elements to be 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multidimensionl arrays

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]

])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a[0,2]=20
a

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
a[0,2]=3
a[0,1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
a[2]=[1,1,1]
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
a[:,2]=[2,2,2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [29]:
np.full ((3,3),10   )

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

Randomly generated arrays

numpy can create arrays filled with random numbers. To ensure the reproducibility, you can set a seed using np.random.seed(). It will generate the exact same random number for each execution.If you remove or change the seed values, the sequence of random number will be changed.


In [30]:
np.random.randn(5,2)

array([[-1.05911268, -0.73814209],
       [ 0.57375473, -0.58419168],
       [-0.20319469, -1.14877248],
       [ 0.38471415, -0.45211625],
       [-1.60701773, -0.63775967]])

In [31]:
np.random.randint(low=0,high=100,size=(5,2))

array([[22, 98],
       [45, 76],
       [41, 17],
       [27, 94],
       [90,  6]])

Element wise operation on entire arrays element by element

In [32]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
a>=2

array([False, False,  True,  True,  True])

In [37]:
# sumarizing of data
# Numpy provides function doe sumarizing array data
a

array([0, 1, 2, 3, 4])

In [38]:
a.std()

1.4142135623730951

In [39]:
a.max()

4

In [41]:
a.min()

0

In [42]:
a.sum()

10